export const MINIMUM_RUN_BUDGET_CENTS = 5_000;
export const STANDARD_RUN_BUDGET_CENTS = 50_000;
export const MAX_RUN_BUDGET_CENTS = STANDARD_RUN_BUDGET_CENTS;
export const WORKER_IDLE_POLL_INTERVAL_MS = 15 * 60 * 1_000;
